"""
Builds the style-conditioned React/TSX fine-tuning dataset.

Two sources combine into the final dataset:
  1. REAL anchor examples — actual components/snippets from Sope's own
     projects (extracted directly below), used as-is.
  2. SYNTHETIC examples — new component-generation tasks, generated by
     calling Gemini with an explicit style guide derived from the real
     code, so the outputs follow the same conventions without just
     copying the anchors.

Run with:
    modal run prep_jsx_data.py

Requires a Modal Secret named "gemini" with key GEMINI_API_KEY set:
    modal secret create gemini GEMINI_API_KEY=xxxx
"""

import modal

app = modal.App("jsx-style-finetune-prep")

volume = modal.Volume.from_name("jsx-finetune-vol", create_if_missing=True)

image = modal.Image.debian_slim(python_version="3.11").pip_install(
    "datasets==2.21.0",
    "google-genai",
)

VOLUME_PATH = "/data"

# ── The explicit style guide, extracted directly from Sope's real files ──
STYLE_GUIDE = """
You are generating React/Next.js component code that must follow this exact
personal coding style. These rules were extracted from real code, follow
them precisely:

1. TAILWIND: Use arbitrary value syntax constantly instead of default scale
   classes. Prefer `text-[13px]`, `font-[600]`, `h-[39px]`, `border-[1.21px]`,
   `w-[330px]` over `text-sm`, `font-semibold`, `h-10`, `border`, `w-80`.
   Pixel-precise arbitrary values are the default, not the exception.

2. COMPONENT DECLARATION: Arrow function components with a `Props` type
   defined just above, destructured directly in the function signature.
   Example shape:
   ```
   type Props = {
     text: string;
   }

   const Button = ({text}: Props) => {
     return (...)
   }

   export default Button
   ```
   Occasionally use `React.FC<Props>` typing style instead, e.g.:
   `const StatusTag: React.FC<StatusTagProps> = ({ status }) => {...}`

3. EXPORT STYLE: Always `export default ComponentName` as a separate
   statement at the bottom of the file, never inline at declaration.

4. COMMENTS: Sparse. Prefer no comments. When a comment does appear, keep
   it short and inline near the relevant line (e.g. `// Item width (230px)
   + gap (8px)`), not full doc-comment blocks above functions.

5. UNION TYPES FOR CONSTRAINED PROPS: When a prop has a fixed set of valid
   string values, define an explicit union type above the component, e.g.:
   ```
   type StatusType = "downloaded" | "drafts" | "saved";
   ```
   and use `Record<StatusType, {...}>` for style/config lookup maps keyed
   by that union.

6. LAYOUT: Frequent use of empty structural divs for spacing/layout, e.g.
   `<div className=""></div>` as an invisible spacer between flex children.

7. STATE: `useState` with explicit TypeScript generics for typed objects,
   e.g. `useState<LoginDetails>({...})`. Simple onChange handlers that pull
   `event.target.name` and `event.target.value` and spread into existing
   state: `setState({ ...state, [name]: value })`.

8. NO SEMICOLON-OBSESSION: Mixed semicolon usage, not strictly enforced
   either way — don't worry about being perfectly consistent on this.

Generate ONLY the code, no explanation before or after. No markdown code
fences. Just the raw .tsx file content.
"""

# Component generation tasks — varied enough to build real signal across
# different UI patterns, all asking for something in the personal style.
GENERATION_TASKS = [
    "A React/Next.js settings page component with toggle switches for notification preferences (email, push, SMS), using local state, no external state library.",
    "A profile card component showing a user's avatar, name, and a status tag (one of 'active', 'away', 'offline'), using a typed union for the status prop.",
    "A search bar component with a text input and a debounced onChange callback prop, styled with Tailwind.",
    "A pagination component with previous/next arrows and numbered page buttons, taking currentPage and totalPages as props.",
    "A modal/dialog component with a title, body content slot (children), and a close button, controlled via an isOpen boolean prop.",
    "A dropdown select component for choosing a country from a fixed list, with the list defined as a union type.",
    "A simple multi-step form wizard header showing step indicators (1, 2, 3) with the current step highlighted.",
    "A file upload component with drag-and-drop styling and a preview of the selected filename.",
    "A sidebar navigation component with icon + label list items, one of which is marked active based on the current route.",
    "A toast/notification banner component with success, error, and warning variants using a typed union and a color lookup map.",
    "A password input component with a show/hide toggle icon and basic strength indicator text.",
    "A card grid component that maps over a list of product objects (name, price, image) and renders a card for each.",
    "A breadcrumb navigation component that takes an array of {label, href} objects and renders them with separators.",
    "A simple accordion/collapsible FAQ item component with an open/closed boolean state.",
    "A rating display component showing filled and unfilled stars based on a numeric rating prop (0-5).",
    "A confirmation dialog component with 'Cancel' and 'Confirm' buttons and a customizable warning message prop.",
    "A tag/chip input component where users can add and remove tags from a list, stored in local state.",
    "A loading skeleton placeholder component for a card layout, using pulse animation classes.",
    "A simple tab navigation component with 3 tabs, switching visible content based on the active tab index.",
    "A footer component with social media icon links and a copyright line with the current year.",
]


@app.function(
    image=image,
    volumes={VOLUME_PATH: volume},
    secrets=[modal.Secret.from_name("gemini")],
    timeout=1800,
)
def generate_dataset():
    import os
    import json
    from google import genai
    from google.genai import types

    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    examples = []

    # ── Part 1: REAL anchor examples from Sope's actual files ──────
    # These are real, hand-written components, used verbatim as the
    # grounding truth the synthetic examples are conditioned to match.
    real_anchors = [
        {
            "prompt": "Write a simple reusable button component with a text label and an arrow icon, styled with Tailwind.",
            "code": '''import React from 'react'

type Props = {
  text: string;
}

const Button = ({text}: Props) => {
  return (
    <div className="w-full border-[1.21px] h-[39px] rounded-full border-white  items-center flex justify-between">

    <div className=""></div>
    <p className=" text-[13px] ">{text}</p>
    <div className="">
    <p className="text-[13px] font-[600] mr-[10px]  ">→</p>
    </div>

  </div>
  )
}

export default Button'''
        },
        {
            "prompt": "Write a status tag component that shows a colored label for one of three states: downloaded, drafts, or saved.",
            "code": '''import React from "react";

type StatusType =
  | "downloaded"
  | "drafts"
  | "saved";

interface StatusTagProps {
  status: StatusType;
}

// StatusTag component
const StatusTag: React.FC<StatusTagProps> = ({ status }) => {
  // Map styles for each status
  const statusStyles: Record<StatusType, { color: string; bgColor: string }> = {
    drafts: {
      color: "#000000",
      bgColor: "#FFCF4B",
    },
    downloaded: {
      color: "#FFFFFF",
      bgColor: "#3B934E",
    },
    saved: {
      color: "#FFFFFF",
      bgColor: "#2563EB",
    },
  };

  const { color, bgColor } = statusStyles[status];

  return (
    <span
      style={{ backgroundColor: bgColor }}
      className="inline-flex items-center gap-2 px-3 py-1 rounded-md text-sm font-medium"
    >
      <span>•</span>
      <span style={{ color }} className="text-[12px] font-[500]">{status.toUpperCase()}</span>
    </span>
  );
};

export default StatusTag;'''
        },
        {
            "prompt": "Write a category filter component that shows a row of clickable category labels, where clicking toggles the selected category.",
            "code": '''import React from "react";

const Filter = ({ category, setCategory }) => {
  const categories = ["cake", "cookie", "pie", "pastry"];
  return (
    <div className="hidden md:flex flex-row items-center w-1/2 justify-between  border-b-bakerzBiteDarkBrown gap-x-[50px]">
      {categories.map((item, key) => (
        <div
          className={`${item === category && "border-[1.5px] border-bakerzBiteDarkBrown rounded-[10px] font-bold"} capitalize p-[5px] cursor-pointer hover:font-bold`}
          key={key}
          onClick={() => {
            setCategory((prev) => (prev === item ? "All" : item));
          }}
        >
          <p className="text-[15.5px] text-bakerzBiteDarkBrown ">{item}</p>
        </div>
      ))}
    </div>
  );
};

export default Filter;'''
        },
        {
            "prompt": "Write a horizontally scrolling image carousel component with left/right arrow controls.",
            "code": '''import React, { useRef } from "react";
import { carousel } from "../../assets/assets";

const Carousel = () => {
  const scrollContainerRef = useRef(null);

  const scrollStep = 238; // Item width (230px) + gap (8px)

  const scrollLeft = () => {
    scrollContainerRef.current.scrollBy({
      left: -scrollStep,
      behavior: "smooth", // Smooth scrolling
    });
  };

  const scrollRight = () => {
    scrollContainerRef.current.scrollBy({
      left: scrollStep,
      behavior: "smooth",
    });
  };

  return (
    <div className="flex absolute flex-nowrap gap-7 rounded-full items-center justify-center flex-row w-[955px] h-[201px] bg-white bg-opacity-70 right-0 left-[50%] bottom-0">
      <div className="flex flex-row items-center gap-4">
        <span onClick={scrollLeft} className="cursor-pointer w-[32px] text-bakerzBiteDarkBrown text-2xl">←</span>

        <span onClick={scrollRight} className="cursor-pointer w-[32px] text-bakerzBiteDarkBrown text-2xl">→</span>
      </div>

      <div
        className="flex flex-row overflow-hidden gap-2 justify-center w-[800px] items-center"
        ref={scrollContainerRef}
      >
        {carousel.map((item, key) => (
          <img
            key={key}
            src={item.image}
            alt=""
            className="min-w-[230px] h-[149px] flex-shrink-0"
          />
        ))}
      </div>
    </div>
  );
};

export default Carousel;'''
        },
        {
            "prompt": "Write a login form component with email/password inputs, a Google sign-in button, and a 'remember me' checkbox.",
            "code": '''"use client";
import React, { useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";

interface LoginDetails {
  email: string;
  password: string;
}

const LoginForm = () => {
  const router = useRouter();
  const [loginDetails, setLoginDetails] = useState<LoginDetails>({
    email: "",
    password: "",
  });

  const onChangeHandler = (event: React.ChangeEvent<HTMLInputElement>) => {
    const name = event.target.name;
    const value = event.target.value;
    setLoginDetails({ ...loginDetails, [name]: value });
  };

  return (
    <div className="w-[330px] flex flex-col gap-5 h-fit">
      <div className="w-full bg-white h-[39px] rounded-full flex items-center gap-2 justify-center ">
        <Image src="/google.svg" width={16} height={16} alt="Google" />
        <p className="text-black font-[500] text-[12px]">
          Continue with Google
        </p>
      </div>

      <div className="flex-col ">
        <input
          className="w-full text-[13px] h-[39px] rounded-full pl-3 mb-3 placeholder:text-[14px] bg-white text-black focus:outline-none focus:ring-0"
          placeholder="Email"
          type="email"
          name="email"
          value={loginDetails.email}
          onChange={onChangeHandler}
        />
        <input
          className="w-full text-[13px] h-[39px] rounded-full pl-3 placeholder:text-[14px] bg-white text-black focus:outline-none focus:ring-0"
          placeholder="Password"
          type="password"
          name="password"
          value={loginDetails.password}
          onChange={onChangeHandler}
        />
      </div>

      <div className="flex gap-2">
        <input type="checkbox" name="remember" id="" />
        <p className="font-[400] text-[11.27px]">Remember me for 30 days</p>
      </div>
    </div>
  );
};

export default LoginForm;'''
        },
    ]

    for ex in real_anchors:
        examples.append({
            "conversations": [
                {"role": "system", "content": "You are an assistant that writes React/Next.js components matching the user's personal coding style: Tailwind arbitrary values, sparse comments, typed Props destructured in the function signature, default export at the bottom of the file."},
                {"role": "user", "content": ex["prompt"]},
                {"role": "assistant", "content": ex["code"]},
            ],
            "source": "real_anchor",
        })

    print(f"Added {len(real_anchors)} real anchor examples.")

    # ── Part 2: SYNTHETIC examples generated to match the style guide ──
    import time

    # Resume support: if a dataset file already exists on the volume from a
    # previous (possibly rate-limited, partially-completed) run, load the
    # synthetic examples already generated so we don't waste calls and time
    # regenerating tasks that already succeeded.
    out_path = f"{VOLUME_PATH}/jsx_dataset.jsonl"
    already_done_prompts = set()
    if os.path.exists(out_path):
        with open(out_path) as f:
            for line in f:
                existing = json.loads(line)
                if existing.get("source") == "synthetic":
                    prompt_text = existing["conversations"][1]["content"]
                    already_done_prompts.add(prompt_text)
                    examples.append(existing)
        if already_done_prompts:
            print(f"Resuming: found {len(already_done_prompts)} synthetic examples already generated, skipping those tasks.")

    print(f"Generating remaining synthetic examples via Gemini...")
    for i, task in enumerate(GENERATION_TASKS):
        if task in already_done_prompts:
            continue
        print(f"  [{i+1}/{len(GENERATION_TASKS)}] {task[:60]}...")

        code = None
        max_retries = 5
        for attempt in range(max_retries):
            try:
                response = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=task,
                    config=types.GenerateContentConfig(
                        system_instruction=STYLE_GUIDE,
                        max_output_tokens=1500,
                    ),
                )
                code = response.text.strip()
                break  # success, stop retrying
            except Exception as e:
                err_str = str(e)
                is_rate_limit = "429" in err_str or "RESOURCE_EXHAUSTED" in err_str
                if is_rate_limit and attempt < max_retries - 1:
                    wait_time = 15 * (attempt + 1)  # 15s, 30s, 45s, 60s...
                    print(f"    Rate limited (attempt {attempt+1}/{max_retries}), waiting {wait_time}s...")
                    time.sleep(wait_time)
                else:
                    print(f"    FAILED (attempt {attempt+1}/{max_retries}): {e}")
                    if not is_rate_limit:
                        break  # don't retry non-rate-limit errors

        if code is None:
            print(f"    Skipping task {i+1} after retries exhausted.")
            continue

        # Strip accidental code fences if the model added them anyway
        if code.startswith("```"):
            code = code.split("\n", 1)[1]
        if code.endswith("```"):
            code = code.rsplit("\n", 1)[0]

        examples.append({
            "conversations": [
                {"role": "system", "content": "You are an assistant that writes React/Next.js components matching the user's personal coding style: Tailwind arbitrary values, sparse comments, typed Props destructured in the function signature, default export at the bottom of the file."},
                {"role": "user", "content": task},
                {"role": "assistant", "content": code},
            ],
            "source": "synthetic",
        })

        # Pace requests to stay under free-tier RPM limits (5-15 RPM
        # depending on tier). A few seconds between calls keeps us
        # comfortably under even the lowest free-tier ceiling.
        time.sleep(5)

    print(f"\nTotal examples: {len(examples)} ({len(real_anchors)} real + {len(examples) - len(real_anchors)} synthetic)")

    # ── Save raw examples as JSONL to the volume ────────────────────
    out_path = f"{VOLUME_PATH}/jsx_dataset.jsonl"
    with open(out_path, "w") as f:
        for ex in examples:
            f.write(json.dumps(ex) + "\n")
    volume.commit()

    print(f"Saved {len(examples)} examples to {out_path}")
    print("NOTE: this is a small dataset (~25 examples). Good for a portfolio")
    print("proof-of-concept, but consider it a starting point, not a large-scale")
    print("training set — expect the model to learn surface style patterns,")
    print("not to generalize broadly from this volume alone.")


@app.local_entrypoint()
def main():
    generate_dataset.remote()